train:
  group: implementing-runs
  dataFolder: ../.mnt/h5
  dataTrain: train.h5
  dataVal: val.h5
  detectionGridSize: [7,7]
  imageSize: [224,224]
  nCategories: 120
  optim_decay: 0
  epochs: 20
  numWorkers: 8
  batchSize: 4 #64
  lr: 0.001

  saveCheckpoints: False

  models:
    f: [32,64,128,256,512]
    classifier:
      nHidden: 256
      dropout: 0.4
